id: bc9e3e3fd8c2433c967628b63712475c
initial_creation_type: ocr
source_metadata:
  volumes:
    8379ee4a4caf4b2d87da48c1166b065a:
      base_file: v115.txt
      image_group_id: I1PD95961
      title: ''
      total_pages: 1880
      volume_number: 116
